export enum TimelineAction {
  CREATED = 'CREATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  SEVERITY_CHANGED = 'SEVERITY_CHANGED',
  DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED',
  DELETED = 'DELETED',
}
